### ISSUE TITLE
搜索框样式

### ISSUE THREAD

**Issue by Du-mg** [Yin-Hongwei/vue-spring-music#166]
![image](https://user-images.githubusercontent.com/104451093/165347124-c1a71b1a-46c6-44e5-8e5b-673d36141c88.png)

**Comment by Yin-Hongwei** [comment]
是最新代码吗，我mac上换了好几个浏览器都正常啊

**Comment by Du-mg** [comment]
谢谢，又拉一个代码显示正常了
